language: "node_js"
node_js:
  - 0.6
  - 0.8
  - 0.10
  - 0.11

services:
  - memcache
  - redis-server

before_script:
  - export MEMCACHIER_SERVERS="localhost:11211"
  - export MEMCACHIER_USERNAME=""
  - export MEMCACHIER_PASSWORD=""
